site_name: Catalog Builder
site_description: "Data Catalogs Made Easy"
site_url: 'https://unytics.io/catalog_builder/'
repo_name: 'unytics/catalog_builder'
repo_url: 'https://github.com/unytics/catalog_builder'
edit_uri: 'edit/main'
copyright: 'Copyright &copy; 2024 Unytics'
docs_dir: '.'
site_dir: '../catalog_builder_website'
exclude_docs: |
  venv/
  .venv/
  .git/
  site/
  docs/
  *.parquet
  *.jsonl
nav:
  - Get Started!: README.md
theme:
  name: material
  # logo: site/assets/logo.png
  # favicon: site/assets/logo.png
  features:
    - tabs
    - content.tabs.link
    - content.code.copy
    # - instant
    # - toc.integrate
    # - navigation.instant
    # - navigation.path
    # - navigation.tabs
    - navigation.tracking
    - navigation.indexes
    - navigation.hide
    # - navigation.expand
markdown_extensions:
  - attr_list
  - md_in_html
  - tables
  - toc:
      toc_depth: 4
      permalink: "Â¶"
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
plugins: []
#   - search
